dist: trusty
sudo: false
language: ruby
rvm:
  - 2.3.0

before_install:
  - npm install

script:
  - node_modules/.bin/lumo validate-yaml.cljs
  - bundle exec jekyll build

deploy:
  provider: script
  script: scripts/deploy
  on:
    branch: master
    condition: "$(git log --format=%s --max-count=1 master)" != "$(TZ=UTC date +%Y-%m-%d) update"
