# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ClojureBridge
email: info@clojurebridge.org
description: ClojureBridge aims to increase diversity within the Clojure
  community by offering free, beginner-friendly Clojure programming workshops
  for women.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clojurebridge.org"
twitter_username: clojurebridge
github_username:  clojurebridge

# Build settings
markdown: kramdown
future: true
